### PR TITLE
Adding Refunded Order Enhanced ECommerce Support

### PR DESCRIPTION
**Pull request by kzap**
Added support for the 'Refunded Order' event using the Enhanced Ecommerce parameters specified by the 
Google Analytics Measurement Protocol [https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#enhanced-ecomm]

I used all parameters that could be used if the productaction (pa) parameter = refund

Wrote tests based on the Completed Order tests

Not sure how to actually do live testing of this with Google Analytics

### CODE REVIEW

**Comment by kzap** [comment]
this also helps part of #5

**Comment by kzap** [comment]
https://developers.google.com/analytics/devguides/collection/protocol/v1/devguide#enhancedecom
shows examples of the actual requests required

enhanced ecommerce requires an event or page to be sent at the same time, so we should add an event for Refunded Order, not sure how to exactly or if i did it right, pls check :)

**Comment by kzap** [comment]
can use CURL or https://ga-dev-tools.appspot.com/hit-builder/ to test

**Comment by kzap** [comment]
sample curl or httpie
```
http -f -v POST https://ssl.google-analytics.com/debug/collect \
	cid=2710159508 \
	tid=UA-27033709-11 \
	cu=USD \
	pa=refund \
	ti=order-id \
	v=1 \
	tr=-1 \
	t=event \
	ec='EnhancedEcommerce' \
	ea="Action not defined" \
	el=event \
	ev=-1 \
	ni=1
```

**Comment by ladanazita** [comment]
@hankim813  :eyes:

**Comment by hankim813** [comment]
@kzap Thanks for the PR! Right now EE is not supported server side yet. This is going to be included in our upcoming sprints. We will make sure to include support for this semantic event.

I know that's frustrating to hear but we would likely want to release the EE features fully when its ready vs shipping out one by one. 

Feel free to correct me if I'm wrong here or want to add more context/eta @sperand-io

**Comment by sperand-io** [comment]
@kzap thanks so much for this! we'll be releasing #31 this evening or tomorrow, which adds support for refundedOrder (in addition to the rest of the enhanced ecom methods!)

**Comment by kzap** [comment]
Thanks. How do we actually find out when a release happens? A merge is
awesome but when will i know its live?

**Comment by hankim813** [comment]
@kzap it should be deployed by now!

**Comment by kzap** [comment]
thanks!

**Pull request closed without merging**
